import { getCurrentWeather } from 'lib/network/currentWeather'
import { InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export const getServerSideProps = async () => {
  const data = await getCurrentWeather(-31.5658899, -68.5366274)
  return {
    props: { data: data },
  }
}

export default function Home({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h2>Api information</h2>
      {JSON.stringify(data.current, null, 3)}
    </div>
  )
}
