import WeatherLocation from '@/components/WeatherLocation/WeatherLocation'
import WeatherSelector from '@/components/WeatherSelector/WeatherSelector'
import { InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import { getCitiesWeather } from '../lib/network/currentWeather'
import styles from '../styles/Home.module.css'

export const getServerSideProps = async () => {
  const data = await getCitiesWeather()
  return {
    props: { data },
  }
}

export default function Home({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <WeatherLocation />
      <WeatherSelector currentWeather={data} />
    </div>
  )
}
