import WeatherSelector from '@/components/WeatherSelector/WeatherSelector'
import { InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import { getCitiesWeather } from '../lib/network/currentWeather'
import styles from '../styles/Home.module.css'

export const getServerSideProps = async () => {
  // -31.5658899, -68.5366274  san Juan Argentina
  // seul Corea 35.1669, 129.0612
  const data = await getCitiesWeather()
  return {
    props: { data },
  }
}

export default function Home({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/*   Data */}
      <WeatherSelector currentWeather={data} />
    </div>
  )
}
